# Generated by Django 3.0.2 on 2020-02-14 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('Branch', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('Period', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Semester', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyingYear',
            fields=[
                ('Studying_Year', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Number', models.CharField(default='', max_length=10)),
                ('Encoding', jsonfield.fields.JSONField(default='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Attendance', jsonfield.fields.JSONField(default='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Period')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
            ],
            options={
                'unique_together': {('Studying_Year', 'Semester', 'Branch', 'Section', 'Period', 'Faculty_ID', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='Allocate_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_of_Week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('Allocate_Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
                ('Allocated_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Allocated_Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Period')),
                ('Allocated_Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Allocated_Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Allocated_Branch', 'Allocate_Studying_Year', 'Allocated_Section', 'Allocated_Period', 'Day_of_Week')},
            },
        ),
    ]
