# Generated by Django 3.0.2 on 2020-02-21 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(upload_to='profile_pics')),
                ('Bio', models.TextField(max_length=500)),
                ('DoB', models.DateField()),
                ('Skills', jsonfield.fields.JSONField(default='')),
                ('Achievements', jsonfield.fields.JSONField(default='')),
                ('Education', jsonfield.fields.JSONField(default='')),
                ('Languages', jsonfield.fields.JSONField(default='')),
                ('Belonging_Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
