# Generated by Django 2.1.9 on 2020-01-25 10:23

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='nm',
        ),
        migrations.AddField(
            model_name='student',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE')], default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='Encoding',
            field=jsonfield.fields.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='Roll_Number',
            field=models.CharField(default='16PA1A', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Studying_Year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=1),
        ),
    ]
