# Generated by Django 2.1.9 on 2020-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0002_auto_20200125_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Studying_Year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=3),
        ),
    ]
