# Generated by Django 3.0.2 on 2020-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
