# Generated by Django 2.1.9 on 2020-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0003_auto_20200125_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_Number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
