# Generated by Django 3.0.2 on 2020-01-29 09:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0004_auto_20200125_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE')], default='CSE', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='Encoding',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll_Number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='Studying_Year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default='I', max_length=5),
        ),
    ]
