# Generated by Django 3.0.2 on 2020-02-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
