# Generated by Django 3.0.2 on 2020-02-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0005_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=150)),
                ('Profile_Picture', models.ImageField(upload_to='profile_pics')),
                ('Bio', models.TextField(max_length=500)),
                ('DoB', models.DateField()),
                ('Gender', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=100)),
                ('Mobile', models.BigIntegerField(max_length=10)),
                ('Github', models.URLField()),
                ('Stackoverflow', models.URLField()),
                ('Facebook', models.URLField()),
                ('Linkedin', models.URLField()),
                ('Twitter', models.URLField()),
                ('Skills', jsonfield.fields.JSONField(default='')),
                ('Achievements', jsonfield.fields.JSONField(default='')),
                ('Education', jsonfield.fields.JSONField(default='')),
                ('Languages', jsonfield.fields.JSONField(default='')),
                ('Belonging_Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
