# Generated by Django 3.0.2 on 2020-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0005_auto_20200129_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Roll_Number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
