# Generated by Django 2.1.9 on 2020-01-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0006_auto_20200129_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('Branch', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('Section', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studying_Year',
            fields=[
                ('Studying_Year', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
    ]
