# Generated by Django 3.0.2 on 2020-02-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
