# Generated by Django 3.0.3 on 2020-03-02 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0007_auto_20200222_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Belonging_Dept',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DoB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_Picture',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Stackoverflow',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
