# Generated by Django 2.1.9 on 2020-01-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0007_branch_section_studying_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studying_Year',
            new_name='Year_of_Study',
        ),
    ]
