# Generated by Django 2.1.9 on 2020-01-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0008_auto_20200130_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year_of_Study',
            new_name='StudyingYear',
        ),
    ]
