# Generated by Django 2.1.9 on 2020-01-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0009_auto_20200130_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branche',
        ),
    ]
