# Generated by Django 2.1.9 on 2020-01-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0010_auto_20200130_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Studying_Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear'),
        ),
    ]
