# Generated by Django 3.0.2 on 2020-02-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0011_auto_20200130_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('Period', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
            ],
        ),
    ]
