# Generated by Django 3.0.2 on 2020-02-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0013_delete_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('Period', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
            ],
        ),
    ]
