# Generated by Django 3.0.2 on 2020-02-02 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0014_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocate_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allocate_Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
                ('Allocated_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Allocated_Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Period')),
                ('Allocated_Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Faculty_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
