# Generated by Django 3.0.2 on 2020-02-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0015_allocate_classes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allocate_classes',
        ),
    ]
