# Generated by Django 3.0.2 on 2020-02-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0021_allocate_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Faculty_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
