# Generated by Django 3.0.2 on 2020-02-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0026_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
