# Generated by Django 3.0.2 on 2020-02-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0030_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Faculty_ID',
        ),
    ]
