# Generated by Django 3.0.2 on 2020-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0033_auto_20200202_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
