# Generated by Django 3.0.2 on 2020-02-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0034_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
