# Generated by Django 3.0.2 on 2020-02-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0036_attendance_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Faculty_ID',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Period',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Studying_Year',
        ),
        migrations.DeleteModel(
            name='Attendance_Video',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
