# Generated by Django 3.0.2 on 2020-02-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0038_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('Studying_Year', 'Semester', 'Branch', 'Section', 'Period', 'Date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Faculty_ID',
        ),
    ]
