# Generated by Django 3.0.2 on 2020-02-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0039_auto_20200203_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
