# Generated by Django 3.0.2 on 2020-02-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0040_auto_20200203_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
