# Generated by Django 3.0.2 on 2020-02-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0042_attendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Faculty_ID',
        ),
    ]
