# Generated by Django 3.0.2 on 2020-02-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0043_auto_20200204_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
