# Generated by Django 3.0.2 on 2020-02-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0045_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Video',
        ),
    ]
