# Generated by Django 3.0.2 on 2020-02-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0047_auto_20200204_1508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
