# Generated by Django 3.0.2 on 2020-02-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0050_auto_20200204_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
