# Generated by Django 3.0.2 on 2020-02-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0051_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Attendance', jsonfield.fields.JSONField(default='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Period')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
            ],
            options={
                'unique_together': {('Studying_Year', 'Semester', 'Branch', 'Section', 'Period', 'Faculty_ID', 'Date')},
            },
        ),
    ]
