# Generated by Django 3.0.2 on 2020-02-04 11:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0052_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocate_classes',
            new_name='Allocate_class',
        ),
    ]
