# Generated by Django 3.0.2 on 2020-02-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0053_auto_20200204_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Studying_Year',
        ),
        migrations.DeleteModel(
            name='Allocate_class',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
