# Generated by Django 3.0.2 on 2020-02-04 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFR1', '0054_auto_20200204_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_Number', models.CharField(default='', max_length=10)),
                ('Encoding', jsonfield.fields.JSONField(default='')),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
            ],
        ),
        migrations.CreateModel(
            name='Allocate_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day_of_Week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('Allocate_Studying_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.StudyingYear')),
                ('Allocated_Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Branche')),
                ('Allocated_Period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Period')),
                ('Allocated_Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Section')),
                ('Allocated_Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFR1.Semester')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Allocated_Branch', 'Allocate_Studying_Year', 'Allocated_Section', 'Allocated_Period', 'Day_of_Week')},
            },
        ),
    ]
