# Generated by Django 3.0.2 on 2020-02-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0055_allocate_class_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
