# Generated by Django 3.0.2 on 2020-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFR1', '0057_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Video',
        ),
    ]
